spring.application.name=lets-play

spring.data.mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}

server.port=${SERVER_PORT}

server.ssl.enabled=true
server.ssl.key-store=${KEYSTORE_PATH}
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.key-store-type=${KEYSTORE_TYPE}
server.ssl.key-alias=${KEYSTORE_ALIAS}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

admin.username=${ADMIN_USERNAME}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}